---
openapi: 3.0.1
info:
  version: "1.0"
  title: System Baseline Backend Service
  description: Service that returns system baselines
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: "{{ path_prefix }}{{ app_name }}/v0"

paths:
  /baselines:
    parameters:
      - $ref: '#/components/parameters/rhIdentityHeader'
    get:
      summary: fetch list of Baseline IDs
      description: "Fetch the list of Baseline IDs"
      operationId: system_baseline.views.v0.get_baseline_ids
      responses:
        '200':
          description: a list of Baseline IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /baselines/{baseline_ids}:
    parameters:
      - $ref: '#/components/parameters/rhIdentityHeader'
      - $ref: '#/components/parameters/BaselineIds'
    get:
      summary: fetch one or more Baseline objects
      description: "Fetch one Baseline object"
      operationId: system_baseline.views.v0.get_baselines_by_ids
      responses:
        '200':
          description: a list of Baseline objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Baseline"
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    InternalServerError:
      description: "An internal server error has occurred."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: "The server could could not process the current request."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Error:
      required:
        - detail
        - status
        - title
        - type
      properties:
        detail:
          type: string
        status:
          type: integer
        title:
          type: string
        type:
          type: string
    Baseline:
      required:
        - bar
      properties:
        bar:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
  parameters:
    rhIdentityHeader:
      in: header
      name: x-rh-identity
      required: true
      schema:
        type: string
      description: "Base64-encoded JSON identity header provided by 3Scale.
                    Contains an account number of the user issuing the
                    request. Format of the JSON:
                    {'identity': {'account_number': '12345678'}}"
    BaselineIds:
      in: path
      name: baseline_ids
      required: true
      schema:
        type: array
        items:
          type: string
